version: '3.9'

services:
  backend:
    image: resume_builder_django
    build: 
      context: ./backend
      dockerfile: ./docker/django/Dockerfile
    command: gunicorn resume_builder.wsgi -w 2 -b 0.0.0.0:${DJANGO_PORT}
    networks:
      - resume_builder_network
      # resume_builder_network:
      #   ipv4_address: 172.19.0.2

  backend_nginx:
    image: resume_builder_django_nginx
    build: ./backend/docker/nginx
    ports: 
      - "${BACKEND_DJANGO_PORT}:${BACKEND_DJANGO_PORT}"
    volumes:
      - ./backend/static:/static
    networks:
      - resume_builder_network
      # resume_builder_network:
      #   ipv4_address: 172.19.0.3
    depends_on:
      - backend

  # react:
  #   image: resume_builder_react_prod
  #   build: 
  #     context: ./frontend
  #     target: production
  #   networks:
  #     resume_builder_network:
  #       ipv4_address: "192.168.18.2"

networks:
  resume_builder_network:
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: "172.19.0.0/16"
