version: '3.9'

services:
  backend:
    image: thequy/resume_builder_django:2.0
    env_file:
      - .env
    command: gunicorn resume_builder.wsgi -w ${GUNICORN_WORKER_COUNT} -b 0.0.0.0:${DJANGO_PORT} --capture-output --access-logfile ./logs/gunicorn-access.log
    networks:
      - resume_builder_network

  backend_nginx:
    image: thequy/resume_builder_django_nginx:1.0
    volumes:
      - ./backend/docker/nginx/templates:/etc/nginx/templates
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    networks:
      - resume_builder_network
    depends_on:
      - backend

  frontend:
    image: thequy/resume_builder_reactjs_nginx:1.0
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend/docker/nginx/templates:/etc/nginx/templates
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - resume_builder_network

networks:
  resume_builder_network:
